name: 'Publish Schedule Action'
description: 'Parses the publishh date from Markdown file'
inputs:
  time_range_minutes:
    description: 'number of minutes the current time that should be included for the check'
    required: true
  content_directory:
    description: 'directory to search for .md files'
    required: false
    default: './'
outputs:
  is_scheduled:
    description: 'boolean value indicating if content was scheduled for the current time period'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  color: 'purple'
  icon: 'clock'
